name: Docker Test
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test-container:
    runs-on: ubuntu-latest
    name: Runs all make tests using the Codespaces Dockerfile
    steps:
      - name: Id Test Step
        id: test
        uses: gmejiamtz/sky130_schematics/.devcontainer@2024.11.23.11.27
      - run: echo "${{ steps.test.outputs.log }}"
