name: Docker Test
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Runs all make tests using the Codespaces Dockerfile
    steps:
      - name: Hello world action step
        id: test
        uses: gmejiamtz/sky130_schematics@2024.11.23.08.53
      - name: Get the output time
        run: echo "Log: ${{ steps.test.outputs.log }}"
